version = 3.10.7
runner.dialect = scala3
docstrings.style = Asterisk
docstrings.wrap = false
maxColumn = 120
indent.defnSite = 2
assumeStandardLibraryStripMargin = true
rewrite.rules = [AvoidInfix, Imports, RedundantBraces, RedundantParens, SortModifiers, RemoveSemicolons]
rewrite.imports.sort = ascii
newlines.afterCurlyLambdaParams = squash
rewrite.redundantBraces {
  maxBreaks = 0
  stringInterpolation = true
  generalExpressions = false
  ifElseExpressions = false
  defnBodies = "all"
}
rewrite.insertBraces {
  settings {
    minBreaks = 1
    countBreakBefore = true
  }
  overrideFor = [{
    minBreaks = 2
    owner = [{
      parents = [
        "Defn\\.(?:Val|Var)"
      ]
    }]
  }]
}
align.preset = more
newlines.topLevelStatementBlankLines = [
  { blanks = 1 }
]
