package fi.oph.tutu.backend.security

object SecurityConstants {
  final val OPH_ORGANISAATIO_OID = "1.2.246.562.10.00000000001"

  final val SECURITY_ROOLI_PREFIX     = "ROLE_"
  final val SECURITY_ROOLI_ESITTELIJA = "APP_TUTU_ESITTELIJA"

  final val SECURITY_ROOLI_ESITTELIJA_FULL =
    SECURITY_ROOLI_PREFIX + SECURITY_ROOLI_ESITTELIJA
}
