export type Tutkinto = {
  id?: string;
  hakemusId: string;
  jarjestys: string;
  nimi?: string;
  oppilaitos?: string;
  aloitusVuosi?: number;
  paattymisVuosi?: number;
  maakoodiUri?: string;
  muuTutkintoTieto?: string;
  todistuksenPaivamaara?: string;
  koulutusalaKoodiUri?: string;
  paaaaineTaiErikoisala?: string;
  todistusOtsikko?: string;
  muuTutkintoMuistio?: string;
  ohjeellinenLaajuus?: string;
  opinnaytetyo?: boolean | null;
  harjoittelu?: boolean | null;
  perustelunLisatietoja?: string;
};
