export type Tutkinto = {
  id?: string;
  hakemusId: string;
  jarjestys: string;
  nimi?: string;
  nimiAlkuperaiskielella?: string;
  nimiKaannoksessa?: string;
  oppilaitos?: string;
  oppilaitosAlkuperaiskielella?: string;
  oppilaitosKaannoksessa?: string;
  aloitusVuosi?: number;
  paattymisVuosi?: number;
  maakoodiUri?: string;
  muuTutkintoTieto?: string;
  todistuksenPaivamaara?: string;
  koulutusalaKoodiUri?: string;
  paaAineTaiErikoisala?: string;
  todistusOtsikko?: string;
  muuTutkintoMuistio?: string;
  ohjeellinenLaajuus?: string;
  opinnaytetyo?: boolean | null;
  harjoittelu?: boolean | null;
  perustelunLisatietoja?: string;
  muokattu?: string | null;
  muokkaaja?: string | null;
};
