name: test-playwright
author: joona.haavisto
description: test-playwright
inputs:
  browser:
    required: true
    description: Playwright project
runs:
  using: composite
  steps:
    - uses: extractions/setup-just@v3
    - uses: ./.github/actions/prepare-next-env
    - name: Create self-signed dev certificates
      shell: bash
      working-directory: ./tutu-frontend
      run: pnpm create-self-signed-dev-certs
    - name: Run playwright
      shell: bash
      working-directory: ./tutu-frontend
      env:
        PLAYWRIGHT_PROJECT: ${{ inputs.browser }}
      run: pnpm start-server-and-test-playwright
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 10
        if-no-files-found: ignore