spring.application.name=tutu-backend

spring.datasource.hikari.maximum-pool-size=20

spring.flyway.locations=classpath:db/migration,classpath:db/repeatable

#swagger-ui config
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.path=/tutu-backend/swagger-ui
springdoc.api-docs.path=/tutu-backend/v3/api-docs

tutu.frontend.dist-location=file:../tutu-frontend/dist/

#1 hr cache
caching.spring.hourTTL=3600000

#1-day cache
caching.spring.dayTTL=86400000

# Spring Security debug logging
# logging.level.org.springframework.security=DEBUG

# CAS debug logging (common CAS client package)
# logging.level.org.jasig.cas.client=DEBUG
# logging.level.org.apereo.cas.client=DEBUG
