name: prepare-scala-env
description: 'Prepare scala env'
runs:
  using: 'composite'
  steps:
    - name: Set up JDK21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'
        cache: 'maven'
        cache-dependency-path: 'tutu-backend/pom.xml'
    - name: Install dependencies
      working-directory: './tutu-backend'
      run: mvn install
