name: prepare-next-env
description: 'Prepare next env'
runs:
  using: 'composite'
  steps:
    - name: Set up npm
      uses: actions/setup-node@v4
      with:
        node-version-file: 'tutu-frontend/.nvmrc'
        cache: 'npm'
        cache-dependency-path: tutu-frontend/package-lock.json
        registry-url: 'https://npm.pkg.github.com'
        scope: '@opetushallitus'
    - name: Cache Next.js
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('package-lock.json') }}-${{ hashFiles('next.config.*', './src/**/*.ts', './src/**/*.tsx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('package-lock.json') }}-
    - name: Install dependencies
      working-directory: ./tutu-frontend
      shell: bash
      run: npm ci
