name: TUTU-käsittely build workflow

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'

env:
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  # Backend
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-scala-env
      - name: Run unit tests
        working-directory: ./tutu-backend
        run: ./mvnw test
  # Frontend
  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-next-env
      - name: Run linter
        working-directory: ./tutu-frontend
        run: npm run lint
