name: TUTU-käsittely build workflow

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'

env:
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_TOKEN: ${{ github.token }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  HUSKY: 0

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  # Backend
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-scala-env
      - name: Run unit tests
        working-directory: ./tutu-backend
        run: ./mvnw test

  # Frontend
  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-next-env
      - name: Run linter
        working-directory: ./tutu-frontend
        run: |
          npm run lint
          npm run prettier

  playwright:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [ chromium, firefox, webkit ]
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v3
      - uses: ./.github/actions/prepare-next-env
      - name: Create self-signed dev certificates
        working-directory: ./tutu-frontend
        run: npm run create-self-signed-dev-certs
      - name: Run playwright
        working-directory: ./tutu-frontend
        env:
          PLAYWRIGHT_ARGS: --project=${{ matrix.browser }}
        run: npm run start-server-and-test-playwright
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 10
          if-no-files-found: ignore
