name: Deploy TUTU-frontend
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        options:
          - dev
          - qa
        required: true
      revision:
        description: Frontend build GH Actions number
        required: true
        type: number

run-name: Deploy TUTU-frontend revision ${{ inputs.revision }} to ${{ inputs.environment }}

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-next-env
      - uses: actions/setup-node@v4
        with:
          node-version-file: "tutu-infra/.nvmrc"
      - name: Configure AWS utility-role credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: ${{ secrets.AWS_TUTU_UTILITY_ROLE_ARN }}
          role-session-name: tutu-frontend-download-build-zip
          aws-region: eu-west-1
      - name: Download build from s3
        working-directory: ./tutu-frontend
        env:
          bucket: ${{ secrets.CDK_FRONTEND_BUILDS_BUCKET_NAME }}
        run: |
          aws s3 cp --no-progress s3://"$bucket"/ga-${{inputs.revision}}.zip build.zip
          unzip build.zip
          cp -R .next/standalone/.next/server .next/server
      - name: Configure AWS dev-role credentials
        if: ${{ inputs.environment == 'dev' }}
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: ${{ secrets.AWS_TUTU_DEV_ROLE_ARN }}
          role-session-name: tutu-frontend-deploy-dev
          aws-region: eu-west-1
      - name: Configure AWS qa-role credentials
        if: ${{ inputs.environment == 'qa' }}
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: ${{ secrets.AWS_TUTU_QA_ROLE_ARN }}
          role-session-name: tutu-frontend-deploy-qa
          aws-region: eu-west-1
      - name: Deploy Next.js app
        working-directory: ./tutu-infra
        env:
          SKIP_OPENNEXT_BUILD: true
        run: |
          npm ci
          npm install -g aws-cdk
          cdk cli-telemetry --disable
          cdk deploy TutuFrontendNextjsStack --require-approval never -c "utility=${{ secrets.AWS_TUTU_UTILITY_ACCOUNT_ID }}" -c "environment=${{ inputs.environment }}" -c "revision=frontendonly"
