name: Deploy TUTU-käsittely
on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        options:
          - dev
          - qa
        required: true
      revision:
        description: Frontend build GH Actions number
        required: true

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODO"
#      - uses: actions/checkout@v4
#      - uses: ./.github/actions/prepare-next-env
#      - name: Install CDK dependencies
#        run: |
#          cd cdk
#          npm ci --prefer-offline
#          npm install -g aws-cdk
#      - name: Configure AWS utility-role credentials
#        uses: aws-actions/configure-aws-credentials@v4.1.0
#        with:
#          role-to-assume: ${{ secrets.AWS_TUTU_UTILITY_ROLE_ARN }}
#          role-session-name: tutu-frontend-download-build-zip
#          aws-region: eu-west-1
#      - name: Download build from s3
#        env:
#          bucket: ${{ secrets.CDK_FRONTEND_BUILDS_BUCKET_NAME }}
#        run: |
#          aws s3 cp --no-progress s3://"$bucket"/valintojen-toteuttaminen/ga-${{inputs.build-number}}.zip build.zip
#          unzip build.zip
#          cp -R .next/standalone/.next/server .next/server # OpenNext v3 needs server-files also in .next/server
#      - name: Configure AWS dev-role credentials
#        uses: aws-actions/configure-aws-credentials@v4.1.0
#        with:
#          role-to-assume: ${{ secrets.AWS_TUTU_DEV_ROLE_ARN }}
#          role-session-name: tutu-frontend-deploy
#          aws-region: eu-west-1
#      - name: Deploy Next.js app
#        env:
#          SKIP_OPENNEXT_BUILD: true
#        run: |
#          cd cdk
#          cdk deploy SovellusStack --require-approval never -c "environment=${{ inputs.environment }}"
