name: Deploy TUTU-käsittely
on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        options:
          - dev
          - qa
        required: true
      stack:
        type: choice
        description: Select cdk stacks
        options:
          - frontend
          - backend
          - all
        required: true
      backend-revision:
        description: Backend build GH Actions number
        required: true
      frontend-revision:
        description: Frontend build GH Actions number
        required: true

jobs:
  deploy-backend:
    if: inputs.stack == 'backend'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy backend
        run: echo "TODO"

  deploy-frontend:
    if: inputs.stack == 'frontend'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy frontend
        run: echo "TODO"

  deploy-all:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy all
        run: echo "TODO"
